services:
  - type: web
    name: kpgreenergy-planner
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WEBAPP_URL
        value: https://script.google.com/macros/s/AKfycbyWKqzx6QvDkl7etKG2v0UEDI7u_Gedgnj-NoEYXy_IrFgKf3tiThOvlWWNCTcyb5qM-w/exec
      - key: GOOGLE_SHEET_URL
        value: https://docs.google.com/spreadsheets/d/1ERBqRnmVGYi7JCqzqTbJMmeh41ShAHWfBmLJW96IC7Y/edit?gid=669434805#gid=669434805
